### ISSUE TITLE
4.0.1 crash with create-fabric-0.5.0.i-1003+1.19.2 in fabric 1.19.2;

### ISSUE THREAD

**Issue by Arborsm** [null2264/CobbleGen#26]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cobblegen'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.ClassCastException: class net.minecraft.class_3576 cannot be cast to class com.tterrag.registrate.fabric.SimpleFlowableFluid$Flowing (net.minecraft.class_3576 and com.tterrag.registrate.fabric.SimpleFlowableFluid$Flowing are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4cf777e8)
	at io.github.null2264.cobblegen.integration.create.CreateFluidInteraction.registerInteraction(CreateFluidInteraction.java:22)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.github.null2264.cobblegen.CobbleGen.onInitialize(CobbleGen.java:29)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more

and latest.log
[latest.log](https://github.com/null2264/CobbleGen/files/11454327/latest.log)

**Comment by null2264** [comment]
Should be fixed in v4.0.2, waiting for the release being built.

**Comment by null2264** [comment]
https://modrinth.com/mod/cobblegen/version/4.0.2+7-ALPHA
