### ISSUE TITLE
Fabric Create integration fails

### ISSUE THREAD

**Issue by yuma-dev** [null2264/CobbleGen#42]
trying to add zinc ore from create makes this pop up:
```[11:06:52] [Server thread/INFO]: [CobbleGen] Loading generators...
[11:06:52] [Server thread/INFO]: [CobbleGen] Loading plugin from cobblegen
[11:06:52] [Server thread/INFO]: [CobbleGen] Loading config...
[11:06:52] [Server thread/INFO]: [CobbleGen] Trying to load config file...
[11:06:52] [Server thread/INFO]: [CobbleGen] 3 generators has been added from config
[11:06:52] [Server thread/INFO]: [CobbleGen] Loaded plugin from cobblegen
[11:06:52] [Server thread/INFO]: [CobbleGen] Loading plugin from cobblegen
[11:06:52] [Server thread/INFO]: [CobbleGen] Create mod detected, loading integration...
[11:06:52] [Server thread/WARN]: [CobbleGen] Something went wrong while loading plugin provided by cobblegen
[11:06:52] [Server thread/ERROR]: [CobbleGen] java.lang.NoClassDefFoundError: com/simibubi/create/content/palettes/AllPaletteStoneTypes
	at io.github.null2264.cobblegen.integration.CreatePlugin.registerInteraction(CreatePlugin.java:26)
	at io.github.null2264.cobblegen.data.FluidInteractionHelper.apply(FluidInteractionHelper.java:133)
	at net.minecraft.server.MinecraftServer.handler$bdb000$cobblegen$applyConfig(MinecraftServer.java:3268)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by null2264** [comment]
Can you specify which version of CobbleGen you're using? Also which MC version you're playing on?

**Comment by yuma-dev** [comment]
5.0.1+1.19.2b23-B
fabric 1.19.2

**Comment by null2264** [comment]
Create 5.1 I'm guessing?

**Comment by GenuineJakob** [comment]
Hi, I noticed the same error in the [Create 2 Mekanism](https://www.curseforge.com/minecraft/modpacks/create-2-mekanism) modpack.

Minecraft 1.19.2
CobbleGen 5.0.2-BETA
Create 0.5.1c

```
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Loading generators...
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Loading plugin from [cobblegen]
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Create mod detected, loading integration...
[Server thread/WARN] [CobbleGen/]: [CobbleGen] Something went wrong while loading plugin provided by [cobblegen]
[Server thread/ERROR] [CobbleGen/]: [CobbleGen] java.lang.NoClassDefFoundError:  com/simibubi/create/content/palettes/AllPaletteStoneTypes
        at TRANSFORMER/cobblegen@5.0.2-BETA/io.github.null2264.cobblegen.integration.CreatePlugin.registerInteraction(CreatePlugin.java:26)
        at TRANSFORMER/cobblegen@5.0.2-BETA/io.github.null2264.cobblegen.data.FluidInteractionHelper.apply(FluidInteractionHelper.java:133)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zjg000$applyConfig(MinecraftServer.java:3893)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:833)
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Loading plugin from [cobblegen]
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Loading config...
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Trying to load config file...
[Server thread/INFO] [CobbleGen/]: [CobbleGen] 3 generators has been added from config
[Server thread/INFO] [CobbleGen/]: [CobbleGen] Loaded plugin from [cobblegen]
[Server thread/INFO] [CobbleGen/]: [CobbleGen] 3 generators has been loaded
[Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.19.2
```

**Comment by null2264** [comment]
Yeah, it's not fully compatible with Create 0.5.1, it *should* still work, just won't show up in JEI. I'll fix it later today since I have a little bit of time off

**Comment by null2264** [comment]
Should be fixed in v5.0.3 (https://github.com/null2264/CobbleGen/commit/1f6ed4c9f2cd794bc3802cf730647f033dd15a96)

**Comment by null2264** [comment]
https://modrinth.com/mod/cobblegen/version/5.0.3+1.19.2b25-BETA-fabric
https://modrinth.com/mod/cobblegen/version/5.0.3+1.19.2b25-BETA-forge

**Comment by GenuineJakob** [comment]
Thank you very much!
