### ISSUE TITLE
Create Fabric compatibility issue - Patch F 

### ISSUE THREAD

**Issue by NatSquared** [null2264/CobbleGen#62]
## Crash
(workaround below)
When playing with Cobblegen (any version) and Create Fabric installed, the game crashes with an error like this one:
```abap
[15/03/2024 20:41:33 PM] ---- Minecraft Crash Report ----
[15/03/2024 20:41:33 PM] // Hey, that tickles! Hehehe!
[15/03/2024 20:41:33 PM] 
[15/03/2024 20:41:33 PM] Time: 2024-03-15 20:41:33
[15/03/2024 20:41:33 PM] Description: Initializing game
[15/03/2024 20:41:33 PM] 
[15/03/2024 20:41:33 PM] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[15/03/2024 20:41:33 PM] 	at net.minecraft.class_310.<init>(class_310.java:458)
[15/03/2024 20:41:33 PM] 	at net.minecraft.client.main.Main.main(Main.java:211)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[15/03/2024 20:41:33 PM] Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.fluids.FluidReactions failed
[15/03/2024 20:41:33 PM] 	at com.simibubi.create.foundation.events.CommonEvents.register(CommonEvents.java:229)
[15/03/2024 20:41:33 PM] 	at com.simibubi.create.Create.onInitialize(Create.java:154)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
[15/03/2024 20:41:33 PM] 	... 6 more
[15/03/2024 20:41:33 PM] Caused by: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.fluids.FluidReactions failed
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[15/03/2024 20:41:33 PM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15/03/2024 20:41:33 PM] 	... 9 more
[15/03/2024 20:41:33 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[15/03/2024 20:41:33 PM] 	... 13 more
[15/03/2024 20:41:33 PM] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for cobblegen.mixins.json:fluid.CreateFluidReactionsMixin from mod cobblegen during activity: [Transform -> Method generator$handlePipeFlowCollision(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lio/github/fabricators_of_create/porting_lib/util/FluidStack;Lio/github/fabricators_of_create/porting_lib/util/FluidStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKEVIRTUAL -> io/github/fabricators_of_create/porting_lib/util/FluidStack::getFluid:()Lnet/minecraft/class_3611;]
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[15/03/2024 20:41:33 PM] 	... 16 more
[15/03/2024 20:41:33 PM] Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.util.FluidStack
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738)
[15/03/2024 20:41:33 PM] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
[15/03/2024 20:41:33 PM] 	... 22 more
[15/03/2024 20:41:33 PM] Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.util.FluidStack
[15/03/2024 20:41:33 PM] 	... 26 more
[15/03/2024 20:41:33 PM] 
[15/03/2024 20:41:33 PM] 
[15/03/2024 20:41:33 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[15/03/2024 20:41:33 PM] ---------------------------------------------------------------------------------------
[15/03/2024 20:41:33 PM] 
[15/03/2024 20:41:33 PM] -- Head --
[15/03/2024 20:41:33 PM] Thread: Render thread
[15/03/2024 20:41:33 PM] Stacktrace:
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
[15/03/2024 20:41:33 PM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[15/03/2024 20:41:33 PM] 	at net.minecraft.class_310.<init>(class_310.java:458)
```

## Known Workaround:  
(while a fix is being created) 
- Navigate to your mods folder
- Rename the cobblestone jar from `.jar` to `.zip`
- Open its contents and find the file called "`cobblegen.mixins.json`"
- Open the file in a text editor
- Remove all of line 9 (`    "fluid.CreateFluidReactionsMixin",`)
- When you're done, it should look like this:
![image](https://github.com/null2264/CobbleGen/assets/33235902/dff290ef-9f92-4137-8c94-7e4852cfcfe7)
- Save the file
- Rename the file back from `.zip` to `.jar`
- Note: this workaround likely disables all create contraption interactions! Use with caution.

**Comment by null2264** [comment]
Lovely, more Porting Lib breaking change

**Comment by null2264** [comment]
Fixing it on GH-63

[builds.zip](https://github.com/null2264/CobbleGen/files/14622967/build-artifacts.zip)

Untested tho, fasting hit hard, probably gonna test it later tonight or tomorrow.
